apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oke-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # UPDATE THIS to your actual GitHub repository URL
    repoURL: 'https://github.com/ahmedibrahim/OKE-App.git'
    targetRevision: HEAD
    path: helm/oke-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
